# Overview
This notebook was created to save and track my Pytorch learning Journey. This notebook is likely to have multiple sequels as this Pytorch is quite a complex and sophisticated framework

# Fundamentals

install CUDA on your local machine if a GPU is available. Don't forget to google cuda is still not available!!!

In [16]:
import torch
torch.cuda.is_available()

True

## tensors

starting with some theory ? what is a tensor ?  
Well, first assuming the existence of a basis of $n$ vectors. then a tensor of rank $m$ is a quantity that is defined by $n^m$ components. Generally this quantity represents a phenomena that can be mathematically modeled by $m$ different vectors. Each component represents a scalar associated with a combination among the possible combinations of choosing $n$ directions (from the basis vectors) $m$ times with repetition.  
HERE IS  A GREAT [REFERENCE](https://www.youtube.com/watch?v=f5liqUk0ZTw)  
resources:  
1. [torch.tensor](https://pytorch.org/docs/stable/tensors.html)
2. [ZTM course](https://www.learnpytorch.io/00_pytorch_fundamentals/)

Nevertheless, let's get more acquainted with tensors in ***Pytorch***   
1. a scalar is a tensor of dimension $0$
2. a vector is a tensor of dimension $1$
3. a matrix is a tensor of dimension $2$
4. an image is a tensor of dimension $3$

In [17]:
# Tensor
t = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]], 
                [[1, 2, 3], 
                 [1, 1, 1],
                  [2,2,2]]])

print(t.shape)
print(t.ndim)

# creating tensors is not usually done manuallym
# here is some good tensor-creation methos
t1 = torch.rand(size=(3, 4))
t2 = torch.rand(size=(2, 3, 4))

print(t1)
print(t2)


torch.Size([2, 3, 3])
3
tensor([[0.6509, 0.1139, 0.0489, 0.0838],
        [0.9171, 0.0033, 0.7360, 0.3477],
        [0.3440, 0.5092, 0.4530, 0.8549]])
tensor([[[0.4281, 0.5576, 0.1108, 0.0435],
         [0.9447, 0.1223, 0.6497, 0.8519],
         [0.1029, 0.1419, 0.1922, 0.9509]],

        [[0.6581, 0.5660, 0.5143, 0.1832],
         [0.9761, 0.0814, 0.0212, 0.2574],
         [0.9625, 0.7300, 0.7563, 0.7645]]])


In [18]:
ones1 = torch.ones(size=(3, 1))
ones2 = torch.ones(size=(3, 2))
# print(ones1, ones2, sep='\n')

# let's create some tensor and extract its characteristics
t = torch.rand(size=(2, 2, 2))
print(f"shape of tensor: {t.shape}")
print(f"data type of tensor: {t.dtype}")
print(f"the device where the tensor is stored: {t.device}")

shape of tensor: torch.Size([2, 2, 2])
data type of tensor: torch.float32
the device where the tensor is stored: cpu


Most of runtime errors would probably be cause by a mismatch of ones of these fields.

In [20]:
# as for operations with matrices, they are the same as in python, numpy
print(ones1 + ones2) # broadcasting works here
print((ones1 + 1) * (ones2 + 3.5)) # should have a (3, 2) with 9.0 for each value

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[9., 9.],
        [9., 9.],
        [9., 9.]])


In [23]:
s = torch.tensor(1)
print(s.shape)
print(s.ndim)

torch.Size([])
0
